version: 2
jobs:
	boot-up:
		# parallelism: 2
		docker:
			- image: circleci/node:7.10.0
			- image: mongo:3.4.4
		steps:
			- checkout
			- run: echo "Begin bootUp"
			- restore_cache:
				key: dependency-cache-{{ checksum "package.json" }}
			- run:
				name: Install npm wee
				command: npm install
			- save_cache:
				key: dependency-cache-{{ checksum "package.json" }}
				paths:
					- node_modules
	build:
		docker:
			- image: circleci/node:7.10.0
			- image: mongo:3.4.4
		steps:
			- run:
				name: Build project
				command: 'gulp build && gulp optimizeImg'
  Test:
		docker:
			- image: circleci/node:7.10.0
			- image: mongo:3.4.4
		steps:
			run:
				name: karma
				command: karma start --single-run

workflows:
	version: 2
	build_and_test:
		jobs:
			- boot-up
			- build: 
				requires:
					- boot-up
			- test:
				requires:
					- build
				# filters:
				# 	branches:
				# 	only: master