version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.0
      - image: mongo:3.4.4
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: Update npm
          command: 'sudo npm install npm@latest'
      
  # Test: