version: 2
jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/node:7.10.0
      - image: mongo:3.4.4
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: Update npm
          command: 'sudo npm install npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build project
          command: 'npm install && gulp build && gulp optimizeImg'
      
  # Test: