version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.0
      - image: mongo:3.4.4
    steps:
      - checkout
      - run: echo "Begin bootUp"
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: Install npm wee
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run: echo "Begin build"
      - run:
        name: Build project
        command: 'gulp build && gulp optimizeImg'
      - save_cache:
        key: build-cache-{{ checksum "build.sha" }}
        paths:
          - View
  test:
    docker:
      - image: circleci/node:7.10.0
      - image: mongo:3.4.4
    steps:
      - run: echo "Begin Tests"
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
        key: build-cache-{{ checksum "build.sha" }}
      - run:
        name: karma
        command: karma start --single-run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build